### ISSUE TITLE
[Todo] General todo's

### ISSUE THREAD

**Issue by vespakoen** [trappsnl/dstore#1]
- [ ] **tests/*** Add more tests
- [x] **config/*** Combine configs, throw error when any required ENV variable is not defined
- [ ] **readme.md** Show responses at curl commands
- [ ] **readme.md** Deploy demo somewhere so curl commands actually work
- [ ] **readme.md** Add contributors
- [x] **readme.md** Describe commands better
